# Generated by Django 6.0.1 on 2026-01-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_practical_index', models.IntegerField(default=0)),
                ('last_theory_index', models.IntegerField(default=0)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.class')),
            ],
        ),
    ]
